services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /home/nben-ais/data/html:/var/www/html
    networks:
      - mynetwork

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - /home/nben-ais/data/html:/var/www/html
    networks:
      - mynetwork

networks:
  mynetwork:
