services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:

volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/nben-ais/data/mysql
      o: bind
      type: none
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nben-ais/data/html
      o: bind