services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports: 
      - "80:80"
      - "443:443"

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - "3306:3306"

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - "9000:9000"
