services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    image: nginx:1337
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    image: mariadb:1337
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    image: wordpress:1337
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

  static-website:
    container_name: static-website
    build: ./requirements/bonus/staticwebsite
    ports:
      - "80:80"
    image: static-website:1337
    restart:
      always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    ports:
      - "8080:8080"
    image: adminer:1337
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/nben-ais/data/mysql
      o: bind
      type: none
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nben-ais/data/html
      o: bind