services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

  # adminer:
  #   image: adminer
  #   build: ./requirements/adminer
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
    driver: local
    driver_opts:
      device: /home/nben-ais/data/mysql
      o: bind
      type: none
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nben-ais/data/html
      o: bind