services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_HOST=${DB_HOST}
    env_file:
      - .env
    restart: always
    networks:
      - mynetwork

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html/wordpress
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/nben-ais/data/html
